### ISSUE TITLE
feat: support github tasklists format for children

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/Starmap#245]
We need to have a discussion around [GitHub tasklists](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists)(currently in private beta) and how we might want to converge our markdown expectations. 

### Some potential areas of concern

Many of these are not priority because of tasklists still being a private beta feature, but the discussion should happen sooner or later so we can handle things appropriately. 

- `children` vs `tasklist`
   - if we want to stick to github as a source of truth and make it easy for users, we should be parsing the items within a `tasklist` as well as `children`
   - we may want to sunset parsing of `children`.

```[tasklist]
### Tasks
- [ ] https://github.com/pln-planning-tools/Starmap/issues/313
- [ ] https://github.com/pln-planning-tools/Starmap/issues/314
- [ ] Set date for sunsetting "children" and communicate to users.
- [ ] Add error (warning) for users still using children, link to this issue.
- [ ] Sunset children parsing on decided date.
```

**Comment by BigLep** [comment]
I agree we should subset ``children`` for tasklist.  Github has gravitation pull (and UI widget) for creating and rendering ``tasklist``.  Let's not fight against it.

**Comment by bajtos** [comment]
I like the idea of preferring native GitHub features like task lists over custom StarMap conventions👍🏻 

A loosely related note: I would love to see support for [GitHub Milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) too. It would be awesome if, for example, I could put a link to a milestone into the `children` array.

**Comment by BigLep** [comment]
I don't think there's much discussion needed here on whether to do it.  I think it's a clear improvement (the request also came in here https://github.com/pln-planning-tools/Starmap/issues/298 ).  I think the discussion now is around when/priority.  If agreed, lets update the title (or create/use another issue) and make clear what the done criteria is.

**Comment by SgtPooki** [comment]
@BigLep I think the main callout is that tasklists are still in beta, but at the time this was created, it was private beta. It is public beta now, so more than likely going to be public-non-beta soon. Github can still change the text or functionality on us, but I think it's less likely now.

**Comment by SgtPooki** [comment]
I created some tasks necessary for calling this done in the description. @whizzzkid anything I missed?

**Comment by SgtPooki** [comment]
Note that a PR is out to solve #313 and #314: https://github.com/pln-planning-tools/Starmap/pull/315

**Comment by AlexxNica** [comment]
@SgtPooki PR #315 made some roadmaps to stop loading. I have created issue #324 and PR #326 to address it.

It seems the bug was related to changes in the parser.

**Comment by SgtPooki** [comment]
We may not want to remove full support for specifying `children:` outside of tasklists.. see https://github.com/pln-planning-tools/Starmap/issues/196.

**Comment by lukemarsden** [comment]
You might want to mention in the docs on starmap.site that tasklists are only available in private beta on GitHub, and you need to join the waitlist before they start working. I was very confused until I saw the "Note" in small text at the top of https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists

**Comment by bajtos** [comment]
FYI - emphasis is mine:

https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist
> Tasklists are in private beta and subject to change. **We have currently paused onboarding to the beta.**
