### ISSUE TITLE
bug: completion rate is invalid for filecoin-station/roadmap#15

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/Starmap#360]
### screenshot of issue in github:

![image](https://user-images.githubusercontent.com/1173416/236302421-1d75c4a9-70b3-4137-ac5e-40e04b35abf1.png)

### resulting JSON when loading locally:

```
{
  "labels": [
    "station core"
  ],
  "completion_rate": 0,
  "due_date": "2023-05-01",
  "html_url": "https://github.com/filecoin-station/roadmap/issues/15",
  "group": "",
  "title": "Station Core 👉 Station Desktop integration",
  "state": "open",
  "node_id": "I_kwDOIUF5GM5fK-t-",
  "parent": {
    "state": "open",
    "group": "children:",
    "title": "Roadmap: Retrieval Markets",
    "html_url": "https://github.com/retrieval-markets-lab/roadmap/issues/1",
    "labels": [
      "starmaps",
      "roadmap"
    ],
    "node_id": "I_kwDOIhfhEc5XfRvq",
    "completion_rate": 0,
    "due_date": "",
    "description": ""
  },
  "children": [],
  "description": "Greatly simplify `Station Desktop` and the product ecosystem in general by letting it leverage `Station Core`."
}
```

**Comment by SgtPooki** [comment]
The black text in the rendered milestone show that no children were recognized: 

![image](https://user-images.githubusercontent.com/1173416/236305027-f4a758c6-52a6-4b90-889c-baa48867734d.png)

**Comment by SgtPooki** [comment]
The value of `result` for https://github.com/filecoin-station/roadmap/issues/15 from https://github.com/pln-planning-tools/Starmap/blob/3dc65092d7e6ded1d9209c0a6ea86e5c116f309c/lib/backend/issue.ts#L27-L37 is below:

```json
{
  "html_url": "https://github.com/filecoin-station/roadmap/issues/15",
  "title": "Station Core 👉 Station Desktop integration",
  "state": "open",
  "node_id": "I_kwDOIUF5GM5fK-t-",
  "body_html": "<p dir=\"auto\">ETA: 2023-05-01</p>\n<p dir=\"auto\">description: Greatly simplify <code class=\"notranslate\">Station Desktop</code> and the product ecosystem in general by letting it leverage <code class=\"notranslate\">Station Core</code>.</p>\n<p dir=\"auto\">Children:</p>\n<ul class=\"contains-task-list\">\n<li class=\"task-list-item\"><input type=\"checkbox\" id=\"\" disabled=\"\" class=\"task-list-item-checkbox\" checked=\"\"> <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load title\" data-id=\"1653584777\" data-permission-text=\"Title is private\" data-url=\"https://github.com/filecoin-station/core/issues/83\" data-hovercard-type=\"pull_request\" data-hovercard-url=\"/filecoin-station/core/pull/83/hovercard\" href=\"https://github.com/filecoin-station/core/pull/83\">filecoin-station/core#83</a></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" id=\"\" disabled=\"\" class=\"task-list-item-checkbox\" checked=\"\"> <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load title\" data-id=\"1676397485\" data-permission-text=\"Title is private\" data-url=\"https://github.com/filecoin-station/core/issues/100\" data-hovercard-type=\"pull_request\" data-hovercard-url=\"/filecoin-station/core/pull/100/hovercard\" href=\"https://github.com/filecoin-station/core/pull/100\">filecoin-station/core#100</a></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" id=\"\" disabled=\"\" class=\"task-list-item-checkbox\"> <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load title\" data-id=\"1655290530\" data-permission-text=\"Title is private\" data-url=\"https://github.com/filecoin-station/desktop/issues/621\" data-hovercard-type=\"pull_request\" data-hovercard-url=\"/filecoin-station/desktop/pull/621/hovercard\" href=\"https://github.com/filecoin-station/desktop/pull/621\">filecoin-station/desktop#621</a></li>\n</ul>\n<p dir=\"auto\">Milestone: <a href=\"https://github.com/filecoin-station/core/milestone/4\">https://github.com/filecoin-station/core/milestone/4</a></p>",
  "body": "ETA: 2023-05-01\r\n\r\ndescription: Greatly simplify `Station Desktop` and the product ecosystem in general by letting it leverage `Station Core`.\r\n\r\nChildren:\r\n- [x] https://github.com/filecoin-station/core/pull/83\r\n- [x] https://github.com/filecoin-station/core/pull/100\r\n- [ ] https://github.com/filecoin-station/desktop/pull/621\r\n\r\nMilestone: https://github.com/filecoin-station/core/milestone/4",
  "labels": [
    "station core"
  ],
  "description": "Greatly simplify `Station Desktop` and the product ecosystem in general by letting it leverage `Station Core`."
}
```

**Comment by SgtPooki** [comment]
It looks like the `children` are in an invalid format: 

```js
const body_text = 'Children:\r\n' +
            '- [x] https://github.com/filecoin-station/core/pull/83\r\n' +
            '- [x] https://github.com/filecoin-station/core/pull/100\r\n' +
            '- [ ] https://github.com/filecoin-station/desktop/pull/621\r\n' +
            '\r\n' + // ...
```

see https://github.com/pln-planning-tools/Starmap/blob/main/User%20Guide.md#children-syntax (deprecated) 
and https://github.com/pln-planning-tools/Starmap/blob/main/User%20Guide.md#tasklist-syntax

**Comment by juliangruber** [comment]
Raw markdown of the issue:

```
ETA: 2023-05-01

description: Greatly simplify `Station Desktop` and the product ecosystem in general by letting it leverage `Station Core`.

Children:
- [x] https://github.com/filecoin-station/core/pull/83
- [x] https://github.com/filecoin-station/core/pull/100
- [ ] https://github.com/filecoin-station/desktop/pull/621

Milestone: https://github.com/filecoin-station/core/milestone/4
```
